server.port=8080

spring.datasource.url=jdbc:mysql://mysql:3306/appdb
spring.datasource.username=appuser
spring.datasource.password=LocalHelp@123


spring.jpa.hibernate.ddl-auto=validate
#spring.sql.init.mode=never

spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.springframework.security=DEBUG
#admin123 -> $2a$10$9W8LwSfdRun4tT3ThxmgA.7W82EkJhMrhnls6Tvm6KD6uyB7Gj.8e
#user123  -> $2a$10$X/jrrQdu4Kz9rPK24rPQEeCUi7D1ZY//dvgDuc9qZFvSxLJl65KK.
