spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:appdb}
spring.datasource.username=${DB_USERNAME:appuser}
spring.datasource.password=${DB_PASSWORD:localhelp}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
